# Generated by Django 3.1.7 on 2021-04-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fweanapp', '0002_imagealbum_imagemedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemedia',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
